import { createContext, useCallback, useContext, useMemo, useState, type ReactNode } from "react";

export type Locale = "en" | "fr";

const en = {
  searchPlaceholder: "Search a region, department or city…",
  searchButton: "Search a place",
  searchEmpty: "No place found.",
  searchRegions: "Regions",
  searchDepartments: "Departments",
  searchCities: "Cities",
  stationsCount: "stations",
  themeToggle: "Toggle dark mode",
  overviewTitle: "Fuel prices in France",
  overviewSubtitle: "Daily national average across {stations} stations, updated {date}.",
  todayAverage: "Average today",
  vs7d: "7 d",
  vs30d: "30 d",
  historyTitle: "Daily average price",
  historyDescription: "Average of the latest price posted by each station, per day.",
  trendTitle: "Trend for the next days",
  trendDescription: "Estimated direction of the national average over the next 7 days. An indication, not a promise.",
  trendUp: "Likely up",
  trendDown: "Likely down",
  trendStable: "Likely stable",
  trendExpected: "Expected change",
  trendConfidence: "{p}% likely",
  trendBrentFell: "Brent in € fell {pct} over the {window} days to {date}",
  trendBrentRose: "Brent in € rose {pct} over the {window} days to {date}",
  trendBrentFlat: "Brent in € barely moved over the {window} days to {date}",
  trendFollow: "pump prices usually follow within ~{lag} days.",
  trendLastWeek: "Last 7 days at the pump: {change}.",
  trendHitRate: "Right {rate} of the time over the last year.",
  trendUnavailable: "Not enough history to estimate a trend.",
  trendMethod: "A linear regression on recent Brent moves in € and last week's pump change. It may be wrong.",
  insightsTitle: "Why prices are moving",
  insightsAiView: "AI view",
  insightsGenerated: "Generated by AI from news on {time} — may be wrong.",
  insightsStale: "Outdated, {age}",
  insightsFresh: "Updated {age}",
  insightsHorizon: "{days} d",
  insightsConfidenceLow: "low confidence",
  insightsConfidenceMedium: "medium confidence",
  insightsConfidenceHigh: "high confidence",
  insightsPriceModel: "Price model: {direction}",
  insightsDrivers: "Drivers",
  insightsSources: "Sources",
  brentTitle: "Brent vs pump price",
  brentDescription: "Brent crude in €/barrel (right axis) and the national average (left axis).",
  brentLabel: "Brent (€/bbl)",
  rankingTitle: "Regions, cheapest first",
  rankingDescription: "Average price today for the selected fuel.",
  nationalAverage: "National average",
  placeRegion: "Region",
  placeDepartment: "Department",
  placeCity: "City",
  placeSubtitle: "{stations} stations · prices updated {date}",
  comparisonTitle: "Compared with France",
  comparisonDescription: "Daily average here vs the national average.",
  stationsTitle: "Stations right now",
  distributionTitle: "Station prices today",
  distributionDescription: "Number of stations per price band, prices updated within 7 days.",
  cheapestTitle: "10 cheapest stations",
  cheapestDescription: "Prices updated within the last 7 days.",
  outOfStockTitle: "Stock-outs",
  outOfStockDescription: "Stations reporting a temporary shortage right now.",
  outOfStockNone: "No stock-out reported",
  stationsLabel: "stations",
  updated: "Updated {when}",
  noStations: "No station with a recent price for this fuel.",
  noHistory: "Fewer than 3 stations: no daily average is published for this city. Showing current station prices.",
  noData: "No data for this fuel here.",
  openMap: "Open in map",
  back: "Back to France",
  githubStar: "Star Jauge on GitHub",
  footerAttribution: "Fuel price data: prix-carburants.gouv.fr (Licence Ouverte)",
  loadError: "Could not load data. Run `pnpm data:build` first.",
  ranges: { "1M": "1M", "3M": "3M", "6M": "6M", "1Y": "1Y", "2Y": "2Y", All: "All" },
};

export type Dictionary = typeof en;

const fr: Dictionary = {
  searchPlaceholder: "Rechercher une région, un département, une ville…",
  searchButton: "Rechercher un lieu",
  searchEmpty: "Aucun lieu trouvé.",
  searchRegions: "Régions",
  searchDepartments: "Départements",
  searchCities: "Villes",
  stationsCount: "stations",
  themeToggle: "Basculer le mode sombre",
  overviewTitle: "Prix des carburants en France",
  overviewSubtitle: "Moyenne nationale quotidienne sur {stations} stations, mise à jour le {date}.",
  todayAverage: "Moyenne du jour",
  vs7d: "7 j",
  vs30d: "30 j",
  historyTitle: "Prix moyen quotidien",
  historyDescription: "Moyenne du dernier prix affiché par chaque station, jour par jour.",
  trendTitle: "Tendance des prochains jours",
  trendDescription: "Direction estimée de la moyenne nationale sur 7 jours. Une indication, pas une promesse.",
  trendUp: "Plutôt en hausse",
  trendDown: "Plutôt en baisse",
  trendStable: "Plutôt stable",
  trendExpected: "Variation attendue",
  trendConfidence: "Probabilité {p} %",
  trendBrentFell: "Le Brent en € a baissé de {pct} sur les {window} jours jusqu'au {date}",
  trendBrentRose: "Le Brent en € a augmenté de {pct} sur les {window} jours jusqu'au {date}",
  trendBrentFlat: "Le Brent en € a peu bougé sur les {window} jours jusqu'au {date}",
  trendFollow: "les prix à la pompe suivent en général sous ~{lag} jours.",
  trendLastWeek: "À la pompe sur 7 jours : {change}.",
  trendHitRate: "Juste dans {rate} des cas sur la dernière année.",
  trendUnavailable: "Historique insuffisant pour estimer une tendance.",
  trendMethod: "Régression linéaire sur les derniers mouvements du Brent en € et la variation à la pompe de la semaine passée. Elle peut se tromper.",
  insightsTitle: "Pourquoi les prix bougent",
  insightsAiView: "Avis de l'IA",
  insightsGenerated: "Généré par IA à partir de l'actualité du {time} — peut se tromper.",
  insightsStale: "Pas à jour, {age}",
  insightsFresh: "Mis à jour {age}",
  insightsHorizon: "{days} j",
  insightsConfidenceLow: "confiance faible",
  insightsConfidenceMedium: "confiance moyenne",
  insightsConfidenceHigh: "confiance élevée",
  insightsPriceModel: "Modèle de prix : {direction}",
  insightsDrivers: "Facteurs",
  insightsSources: "Sources",
  brentTitle: "Brent et prix à la pompe",
  brentDescription: "Brent en €/baril (axe de droite) et moyenne nationale (axe de gauche).",
  brentLabel: "Brent (€/baril)",
  rankingTitle: "Régions, de la moins chère à la plus chère",
  rankingDescription: "Prix moyen du jour pour le carburant choisi.",
  nationalAverage: "Moyenne nationale",
  placeRegion: "Région",
  placeDepartment: "Département",
  placeCity: "Ville",
  placeSubtitle: "{stations} stations · prix mis à jour le {date}",
  comparisonTitle: "Comparé à la France",
  comparisonDescription: "Moyenne quotidienne ici et moyenne nationale.",
  stationsTitle: "Les stations en ce moment",
  distributionTitle: "Prix des stations aujourd'hui",
  distributionDescription: "Nombre de stations par tranche de prix, prix mis à jour depuis moins de 7 jours.",
  cheapestTitle: "Les 10 stations les moins chères",
  cheapestDescription: "Prix mis à jour au cours des 7 derniers jours.",
  outOfStockTitle: "Ruptures",
  outOfStockDescription: "Stations signalant une rupture temporaire en ce moment.",
  outOfStockNone: "Aucune rupture signalée",
  stationsLabel: "stations",
  updated: "Mis à jour {when}",
  noStations: "Aucune station avec un prix récent pour ce carburant.",
  noHistory: "Moins de 3 stations : pas de moyenne quotidienne publiée pour cette ville. Voici les prix actuels.",
  noData: "Pas de données pour ce carburant ici.",
  openMap: "Voir sur la carte",
  back: "Retour à la France",
  githubStar: "Mettre une étoile à Jauge sur GitHub",
  footerAttribution: "Données de prix : prix-carburants.gouv.fr (Licence Ouverte)",
  loadError: "Impossible de charger les données. Lancez d'abord `pnpm data:build`.",
  ranges: { "1M": "1M", "3M": "3M", "6M": "6M", "1Y": "1A", "2Y": "2A", All: "Tout" },
};

const DICTIONARIES: Record<Locale, Dictionary> = { en, fr };

type StringKey = { [K in keyof Dictionary]: Dictionary[K] extends string ? K : never }[keyof Dictionary];

interface I18n {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  dict: Dictionary;
  t: (key: StringKey, params?: Record<string, string | number>) => string;
  price: (thousandths: number) => string;
  euros: (value: number, digits?: number) => string;
  cents: (value: number, signed?: boolean) => string;
  percent: (value: number, signed?: boolean, digits?: number) => string;
  integer: (value: number) => string;
  date: (iso: string, style?: "short" | "long") => string;
  dateTime: (iso: string) => string;
}

const I18nContext = createContext<I18n | null>(null);
const STORAGE_KEY = "jauge.locale";

function initialLocale(): Locale {
  const stored = typeof localStorage !== "undefined" ? localStorage.getItem(STORAGE_KEY) : null;
  return stored === "fr" || stored === "en" ? stored : "en";
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(initialLocale);

  const setLocale = useCallback((next: Locale) => {
    localStorage.setItem(STORAGE_KEY, next);
    document.documentElement.lang = next;
    setLocaleState(next);
  }, []);

  const value = useMemo<I18n>(() => {
    const dict = DICTIONARIES[locale];
    const tag = locale === "fr" ? "fr-FR" : "en-GB";
    const fixed = (digits: number) =>
      new Intl.NumberFormat(tag, { minimumFractionDigits: digits, maximumFractionDigits: digits });
    const price3 = fixed(3);
    const one = fixed(1);
    const int = new Intl.NumberFormat(tag);
    const short = new Intl.DateTimeFormat(tag, { day: "numeric", month: "short", timeZone: "UTC" });
    const long = new Intl.DateTimeFormat(tag, { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" });
    const dateTime = new Intl.DateTimeFormat(tag, {
      day: "numeric",
      month: "short",
      hour: "2-digit",
      minute: "2-digit",
      timeZone: "UTC",
    });
    const sign = (value: number, signed: boolean) => (signed && value > 0 ? "+" : value < 0 ? "−" : "");
    return {
      locale,
      setLocale,
      dict,
      t: (key, params) =>
        (dict[key] as string).replace(/\{(\w+)\}/g, (_, name: string) => String(params?.[name] ?? `{${name}}`)),
      price: (thousandths) => `${price3.format(thousandths / 1000)} €/L`,
      euros: (value, digits = 0) => `${fixed(digits).format(value)} €`,
      cents: (value, signed = true) => `${sign(value, signed)}${one.format(Math.abs(value))} c`,
      percent: (value, signed = true, digits = 1) =>
        `${sign(value, signed)}${fixed(digits).format(Math.abs(value))}${locale === "fr" ? " %" : "%"}`,
      integer: (value) => int.format(value),
      date: (iso, style = "short") => (style === "short" ? short : long).format(new Date(`${iso.slice(0, 10)}T00:00:00Z`)),
      // Station timestamps are French local time without zone; format them as-is.
      dateTime: (iso) => dateTime.format(new Date(`${iso}Z`)),
    };
  }, [locale, setLocale]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

// eslint-disable-next-line react-refresh/only-export-components
export function useI18n(): I18n {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n must be used inside I18nProvider");
  return context;
}
